### ISSUE TITLE
Bug in serious riddle (mobile)

### ISSUE THREAD

**Issue by ripa1995** [runtime-machines/runtimemachines.io#41]
## Bug description

See picture.

- Would you like to work on a fix? [y/n] N
 
## To Reproduce

1. play riddle from mobile
2. SQL question, answer not aligned.

## Expected behavior

Answer aligned on left.

## Screenshots
![Image_20221219_093726_998](https://user-images.githubusercontent.com/83774306/208395425-6175bce5-10c4-4ec3-9cf6-ab9d905adb09.png)

## Environment

- OS: [e.g. Ubuntu 20.04]
- Node version: [e.g. 16.18.1]

**Comment by gianlucastefanoni** [comment]
![mobile_fix](https://user-images.githubusercontent.com/108808995/208420871-6770f3f9-1bbf-45fc-bb25-e476dfdfe77a.PNG)

Do you want something like this?
The alternative is to make a grid but it will look like this, and also the typewriter animation would look different:

![mobile_fix2](https://user-images.githubusercontent.com/108808995/208421221-90558afa-300d-4cce-8ced-79904f304e1f.PNG)

**Comment by ripa1995** [comment]
Fixed in #46
